const KEY="nox_hell_v1";
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{onboarded:false,cart:1,addresses:[],orders:[]};
const PRODUCT={name:"HELL",price:35,weight:500};
const $=s=>document.querySelector(s);
const money=n=>n.toFixed(2).replace(".",",")+" €";
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateBadge()}
function shipping(q){return 5+Math.max(0,Math.ceil((q-4)/2))*2}
function updateBadge(){$("#cartBadge").textContent=state.cart}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function pageHome(){return `<section class="page"><div class="hero"><div class="symbol">HELL</div><div class="eyebrow">NØX</div><h1>HELL</h1><div class="price">${money(PRODUCT.price)}</div><div class="muted">${PRODUCT.weight} g</div><div class="qty"><button onclick="changeQty(-1)">−</button><strong>${state.cart}</strong><button onclick="changeQty(1)">+</button></div><button class="btn red" onclick="go('cart')">In den Warenkorb</button></div><div class="card"><div class="row"><span class="muted">Versand</span><strong>ab ${money(5)}</strong></div><p class="muted">1–4 Stück: 5,00 € · danach +2,00 € je 2 weitere Stück.</p></div></section>`}
function changeQty(n){state.cart=Math.max(1,state.cart+n);save();render("home")}
function cartHTML(){let sub=state.cart*35, ship=shipping(state.cart), total=sub+ship;return `<section class="page"><div class="eyebrow">NØX</div><h2>Warenkorb</h2><div class="card"><div class="row"><div><strong>HELL</strong><div class="muted">500 g pro Stück</div></div><strong>${money(35)}</strong></div><div class="qty"><button onclick="changeQty(-1)">−</button><strong>${state.cart}</strong><button onclick="changeQty(1)">+</button></div><div class="summary-line row"><span>Zwischensumme</span><span>${money(sub)}</span></div><div class="summary-line row"><span>Versand</span><span>${money(ship)}</span></div><div class="row total"><span>Gesamt</span><span>${money(total)}</span></div></div><button class="btn red" onclick="go('checkout')">Zur Bestellung</button></section>`}
function addressesHTML(){return `<section class="page"><div class="eyebrow">NØX</div><h2>Meine Adressen</h2>${state.addresses.map((a,i)=>`<div class="card address"><div class="row"><label><input class="radio" type="radio" name="sel" ${a.selected?'checked':''} onchange="selectAddress(${i})"> <strong>${esc(a.first)} ${esc(a.last)}</strong></label><button class="ghost danger" onclick="deleteAddress(${i})">Löschen</button></div><p>${esc(a.street)} ${esc(a.no)}<br>${esc(a.zip)} ${esc(a.city)}<br>${esc(a.country)}${a.phone?'<br>'+esc(a.phone):''}</p></div>`).join("")}<div class="card"><h3>Adresse hinzufügen</h3><div class="grid">${["first|Vorname","last|Nachname","street|Straße","no|Hausnummer","zip|PLZ","city|Ort","country|Land","phone|Telefonnummer (optional)"].map(x=>{let [k,l]=x.split("|");return `<div class="field"><label>${l}</label><input id="a_${k}" ${k==="phone"?"type=tel":""}></div>`}).join("")}</div><br><button class="btn" onclick="addAddress()">Adresse speichern</button></div></section>`}
function addAddress(){let keys=["first","last","street","no","zip","city","country","phone"],a={};keys.forEach(k=>a[k]=$(`#a_${k}`).value.trim());if(!a.first||!a.last||!a.street||!a.no||!a.zip||!a.city||!a.country){toast("Bitte fülle alle Pflichtfelder aus.");return}a.selected=state.addresses.length===0;state.addresses.forEach(x=>x.selected=false);state.addresses.push(a);save();render("addresses")}
function selectAddress(i){state.addresses.forEach((a,j)=>a.selected=j===i);save();toast("Lieferadresse ausgewählt.")}
function deleteAddress(i){state.addresses.splice(i,1);if(state.addresses.length&&!state.addresses.some(a=>a.selected))state.addresses[0].selected=true;save();render("addresses")}
function selected(){return state.addresses.find(a=>a.selected)}
function checkoutHTML(){let a=selected(),sub=state.cart*35,ship=shipping(state.cart),total=sub+ship;if(!a)return `<section class="page"><h2>Lieferadresse</h2><div class="card"><p>Bitte füge zuerst eine Lieferadresse hinzu und wähle sie aus.</p><button class="btn" onclick="go('addresses')">Zu den Adressen</button></div></section>`;return `<section class="page"><div class="eyebrow">Letzter Schritt</div><h2>Bestellung prüfen</h2><div class="card"><div class="summary-line row"><span>HELL × ${state.cart}</span><span>${money(sub)}</span></div><div class="summary-line row"><span>Versand</span><span>${money(ship)}</span></div><div class="row total"><span>Gesamt</span><span>${money(total)}</span></div></div><div class="card"><h3>Lieferadresse</h3><p>${esc(a.first)} ${esc(a.last)}<br>${esc(a.street)} ${esc(a.no)}<br>${esc(a.zip)} ${esc(a.city)}<br>${esc(a.country)}${a.phone?'<br>'+esc(a.phone):''}</p><button class="btn secondary" onclick="go('addresses')">Adresse ändern</button></div><button class="btn red" onclick="sendOrder()">Bestellung verbindlich senden</button></section>`}
function ordersHTML(){if(!state.orders.length)return `<section class="page"><div class="empty"><h2>Keine Bestellungen</h2><p>Hier erscheinen deine lokal gespeicherten Bestellungen.</p></div></section>`;return `<section class="page"><div class="eyebrow">NØX</div><h2>Meine Bestellungen</h2>${state.orders.slice().reverse().map(o=>`<div class="card"><div class="row"><strong>${o.id}</strong><span class="muted">${o.date}</span></div><p>HELL × ${o.qty}<br>Gesamt: <strong>${money(o.total)}</strong><br>Status: ${o.status}</p><details><summary>Details</summary><p>${esc(o.address)}</p></details></div>`).join("")}</section>`}
function render(p="home"){let html=p==="home"?pageHome():p==="cart"?cartHTML():p==="addresses"?addressesHTML():p==="checkout"?checkoutHTML():ordersHTML();$("#main").innerHTML=html;document.querySelectorAll("[data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===p));updateBadge()}
function go(p){render(p)}
document.addEventListener("click",e=>{let b=e.target.closest("[data-page]");if(b)go(b.dataset.page)});
function toast(t){$("#toast").innerHTML=`<span class="toast">${esc(t)}</span>`;setTimeout(()=>$("#toast").innerHTML="",2500)}
async function sendOrder(){let a=selected();if(!a){toast("Bitte wähle eine Lieferadresse aus.");return}let sub=state.cart*35,ship=shipping(state.cart),total=sub+ship,id="NOX-"+new Date().toISOString().slice(0,10).replaceAll("-","")+"-"+Math.random().toString(36).slice(2,7).toUpperCase(),o={id,date:new Date().toLocaleString("de-DE"),qty:state.cart,total,status:"Gesendet",address:`${a.first} ${a.last}, ${a.street} ${a.no}, ${a.zip} ${a.city}, ${a.country}${a.phone?`, Tel. ${a.phone}`:""}`};try{let r=await fetch("/api/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...o,addressObj:a,sub,ship})});if(!r.ok)throw 0}catch(e){toast("Übermittlung momentan nicht möglich.");return}state.orders.push(o);save();$("#main").innerHTML=`<section class="page success"><div class="check">✓</div><h2>Bestellung übermittelt</h2><p>Deine Bestellung <strong>${o.id}</strong> wurde erfolgreich übermittelt.</p><div class="card"><strong>Bitte überweise ${money(total)} auf das bereits bekannte Konto des Verkäufers.</strong><p class="muted">Deine Bestellung wird nach Zahlungseingang bearbeitet.</p></div><button class="btn" onclick="go('orders')">Meine Bestellungen</button></section>`}
let idleTimer;function resetIdle(){clearTimeout(idleTimer);idleTimer=setTimeout(()=>$("#idle").classList.remove("hidden"),120000)}
["click","touchstart","scroll","keydown"].forEach(ev=>document.addEventListener(ev,()=>{if(!$("#idle").classList.contains("hidden"))$("#idle").classList.add("hidden");resetIdle()},{passive:true}));
function onboarding(){if(state.onboarded)return;let steps=[["HELL","Einfach. Direkt. Vertraulich."],["1","Wähle deine gewünschte Menge und lege HELL in den Warenkorb."],["2","Speichere eine oder mehrere Lieferadressen."],["3","Prüfe deine Bestellung und sende sie direkt an den Verkäufer."],["NØX","Deine Privatsphäre","Diese App arbeitet lokal auf deinem Gerät. Deine persönlichen Daten werden geschützt und vertraulich behandelt und ausschließlich für die Abwicklung und den Versand deiner Bestellung verwendet."]];let i=0;let box=()=>{$("#onboarding").innerHTML=`<div class="modal-box"><div class="symbol">${steps[i][0]}</div><h2>${steps[i][1]}</h2>${steps[i][2]?`<p class="muted">${steps[i][2]}</p>`:""}<button class="btn red" onclick="nextOnboard()">${i===steps.length-1?"Verstanden":"Weiter"}</button></div>`;$("#onboarding").classList.remove("hidden")};window.nextOnboard=()=>{if(i===steps.length-1){state.onboarded=true;save();$("#onboarding").classList.add("hidden");return}i++;box()};box()}
render();onboarding();resetIdle();
